### ISSUE TITLE
possible bug in InterfaceEquation?

### ISSUE THREAD

**Issue by yh-kwok** [devsim/devsim#133] opened 2024-03-18 07:44 UTC
**Describe the bug**
For continuous interface, the if condition regarding active nodes in assembling matrix is different from the if condition in assembling RHS.
 
InterfaceEquation.cc line 435:
if (!(activeNodes0.count(node0)) && (activeNodes1.count(node1)))

Is it a bug or intended?

**Additional context**
This line is introduced in commit
https://github.com/devsim/devsim/commit/d0304991758c2d5199fba6dfc8b50fe16241bef8

**Comment by tcaduser** [comment] 2024-03-19 01:45
Hi @yh-kwok,

Thanks for looking at the code.  It looks like a bug and I'll have time to fix it this coming weekend.  This also requires running the regression tests to make sure any changes in results are intended.

Please note the almost all nodes at interfaces are active, except in some cases such as a contact and interface share the same node, and are solving the same equation.  The nodes on both sides of the interface should be active in order to be able to assemble the equation.

I can provide scripts that will remove nodes from an interface if they intersect a contact.

**Comment by yh-kwok** [comment] 2024-03-21 03:36
Thank you for the confirmation and your work

**Comment by tcaduser** [comment] 2024-03-23 01:01
This is now checked in.  The regression tests didn't change, but I think that it can have an effect for certain meshes.

**Closed by tcaduser** 2024-03-23 01:01 UTC
Labels: bug

**Comment by tcaduser** [comment] 2024-03-23 14:12
For your reference, in case you run into a mesh troubleshooting simulation.

https://forum.devsim.org/t/troubleshooting-a-faulty-mesh/259/1
